### ISSUE TITLE
This extension is no longer available because it doesn't follow best practices for Chrome extensions.

### ISSUE THREAD

**Issue by nikhilmaddirala** [dbuezas/chrome-palette#3]
Any plans to fix this?

![image](https://github.com/user-attachments/assets/b74b8405-78f1-40e5-a32b-e65f8a975d80)

**Comment by dbuezas** [comment]
Yes, although it will be a faster and modern looking rewrite:)

**Comment by nikhilmaddirala** [comment]
Amazing - looking forward! 😊

**Comment by dbuezas** [comment]
I just uploaded the new version, it is a full rewrite so it will have to go through the whole google review process again and may take a while.

It's smaller, faster, has more features and a new look:

<img width="616" alt="image" src="https://github.com/user-attachments/assets/42a5833c-1d79-4317-bd48-4c53d1131629">
<img width="621" alt="image" src="https://github.com/user-attachments/assets/1e40dd79-f1ef-46af-8a2f-5dd0b4a33d74">

**Comment by dbuezas** [comment]
Alright! It's live. That went faster than expected. Lmk what you think :)

**Comment by nikhilmaddirala** [comment]
It's amazing, thank you! I just left a 5 star review for your extension.

> It's smaller (half the size), faster (half the startup time), has more features and a new look:

Yes, I notice it's faster, but what are the new features?

**Comment by dbuezas** [comment]
Happy to hear!
The new features are many more links to settings, nothing groundbreaking
